"""
Unit tests for the Lockpick client module
"""
import unittest, pdb

from lockpyck import Lockpick

# For unit testing only; this user doesn't exist in production. Seriously, don't even bother trying ...
_TESTHOST = 'https://localhost:3001'
_TESTUSER = 'test'
_TESTPASS = 'test'
        
# Test XML

_TESTKDM =\
"""
    <?xml version="1.0" encoding="UTF-8" standalone="no" ?><DCinemaSecurityMessage xmlns="http://www.smpte-ra.org/schemas/430-3/2006/ETM" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns:enc="http://www.w3.org/2001/04/xmlenc#">
    <!-- Generated by Wailua Version 0.5.29 -->
    <AuthenticatedPublic Id="ID_AuthenticatedPublic">
    <MessageId>urn:uuid:f1242cbc-6c70-46fb-ab22-1f8a220ed043</MessageId>
    <MessageType>http://www.smpte-ra.org/430-1/2006/KDM#kdm-key-type</MessageType>
    <AnnotationText>GREAT-W-SILENC_FTR_F_EN-XX_UK_20_2K_BFI_20110303_AAM_OV ~ KDM for SM.Dolby256-CAT862-0007dc02</AnnotationText>
    <IssueDate>2011-12-30T15:16:04+00:00</IssueDate>
    <Signer>
    <dsig:X509IssuerName>dnQualifier=vVfvxXz1gOzEDwm2NoiJtcy4REQ=,CN=.192.168.254.3,OU=.cc-ra-1a.s430-2.ca.cinecert.com,O=.ca.cinecert.com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>38981</dsig:X509SerialNumber>
    </Signer>
    <RequiredExtensions>
    <KDMRequiredExtensions xmlns="http://www.smpte-ra.org/schemas/430-1/2006/KDM">
    <Recipient>
    <X509IssuerSerial>
    <dsig:X509IssuerName>dnQualifier=4dl0oY64k/gzxFwgTB0eISmnFhg=,CN=.Cinea.MFGCA.1,O=DC256.Cinea.Com,OU=MFGCA1.DC256.Cinea.Com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>7584</dsig:X509SerialNumber>
    </X509IssuerSerial>
    <X509SubjectName>dnQualifier=LXmIGORT9YabUQFGaDNh015mHtc=,CN=SM.Dolby256-CAT862-0007dc02,O=DC256.Cinea.Com,OU=DolbyMediaBlock</X509SubjectName>
    </Recipient>
    <CompositionPlaylistId>urn:uuid:1f5264fa-efb1-4eb2-9b19-f29ad4a3b9e8</CompositionPlaylistId>
    <ContentTitleText>GREAT-W-SILENC_FTR_F_EN-XX_UK_20_2K_BFI_20110303_AAM_OV</ContentTitleText>
    <ContentKeysNotValidBefore>2011-12-30T00:00:00+00:00</ContentKeysNotValidBefore>
    <ContentKeysNotValidAfter>2012-01-13T23:59:00+00:00</ContentKeysNotValidAfter>
    <AuthorizedDeviceInfo>
    <DeviceListIdentifier>urn:uuid:e8f099a2-78af-4fe4-8ca2-c98f3524e09b</DeviceListIdentifier>
    <DeviceList>
    <CertificateThumbprint>2jmj7l5rSw0yVb/vlWAYkK/YBwk=</CertificateThumbprint>
    </DeviceList>
    </AuthorizedDeviceInfo>
    <KeyIdList>
    <TypedKeyId>
    <KeyType>MDIK</KeyType>
    <KeyId>urn:uuid:82acba1e-0465-4bc3-b852-7211a44d93a5</KeyId>
    </TypedKeyId>
    <TypedKeyId>
    <KeyType>MDAK</KeyType>
    <KeyId>urn:uuid:ca657add-3c29-4f7c-bd06-59181c7935fc</KeyId>
    </TypedKeyId>
    </KeyIdList>
    <ForensicMarkFlagList>
    <ForensicMarkFlag>http://www.smpte-ra.org/430-1/2006/KDM#mrkflg-picture-disable</ForensicMarkFlag>
    <ForensicMarkFlag>http://www.smpte-ra.org/430-1/2006/KDM#mrkflg-audio-disable</ForensicMarkFlag>
    </ForensicMarkFlagList>
    </KDMRequiredExtensions>
    </RequiredExtensions>
    <NonCriticalExtensions/>
    </AuthenticatedPublic>
    <AuthenticatedPrivate Id="ID_AuthenticatedPrivate"><enc:EncryptedKey xmlns:enc="http://www.w3.org/2001/04/xmlenc#">
    <enc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
    <ds:DigestMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    </enc:EncryptionMethod>
    <enc:CipherData>
    <enc:CipherValue>ldyUs+5E8sMpzWFvDWJDY5A5SxRTf7W9w29g6O8IEiiNf4ZAJJyDI8epAlLTifUdvgjdDgLMz+n4
    5q87iuZFrKJquVQqabvyFODiuwJxDw3GcP3gr3hVzfYAe/vGeIFIGSP6M9Dslhinzn9lNjzkAhYf
    d7jcmnxTeXfRsYTs1SjZVWQR3K6U4cOj7lLi2YXG1T9bQC1G650FPAfSrr1ndnPGESxMCPDIQzJJ
    D37aPu4vtxQcrp0Kj7qJEgNYwMbdCM0i63i4vcx1PzcMc4AuXDMfQQ6gRfbQvg1QvDdDulc4StBX
    q8peaylkjvZEPHub6mt+iyOz33BNxDjrU2odGQ==</enc:CipherValue>
    </enc:CipherData>
    </enc:EncryptedKey><enc:EncryptedKey xmlns:enc="http://www.w3.org/2001/04/xmlenc#">
    <enc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
    <ds:DigestMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    </enc:EncryptionMethod>
    <enc:CipherData>
    <enc:CipherValue>CB3i1NewePzlElbYJtKAuwWP8qMSbvgPu3mGUl86joHrwoR7WsHgwZuPGXZq4gRa6ozoXaYPWvha
    Pv8HfFaCmT/DogouBc5FlbkFZzZWltn+kClmdtic84wpi8fXbKaC/tJjrPQNL7e9Ob11d6m0PAXz
    9Trk+vGF4oZ/ClU8lsNDqQqIVBj5rt2SMn/SeASNnA3nD0yXjfxcwzfu8pH9Fw7Z5Aaur05nqiWm
    WWGu1vTnSc5hWOPJRRJ8SE+l959dReuMTY11oz6x03zFUjuN3QzspJZeDQi1i2sv8ky6R4K9SG+C
    t9/blha8ALpylsCUUXn84SkJt2ZERfc6zLoFaw==</enc:CipherValue>
    </enc:CipherData>
    </enc:EncryptedKey></AuthenticatedPrivate>
    <dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
    <dsig:SignedInfo>
    <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/>
    <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
    <dsig:Reference URI="#ID_AuthenticatedPublic">
    <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
    <dsig:DigestValue>+XeHRE8Aj/T/OHmA221w9h3XCbrpyicPiqpJTkRjrw8=</dsig:DigestValue>
    </dsig:Reference>
    <dsig:Reference URI="#ID_AuthenticatedPrivate">
    <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
    <dsig:DigestValue>nwBpqtTUFfcR+MuuuihiGI1b8IDvshlvZLBC2ZExw4M=</dsig:DigestValue>
    </dsig:Reference>
    </dsig:SignedInfo>
    <dsig:SignatureValue>2Sml7tmRFoWfi4xrJRgmwMfG0chZ1z0o6/v/2ZdsaerwXXCzrKT0U6EEvAeMMBiH
    p7vVObfp4T6vDc0ou5/dWYpRpIJ6Fb6ul3fUhiN0YCQwm65wZ7OPvGYge9ylxgMv
    VB57qJjIT0KQXrYB3+9x0Mjj2uvMmvQclT7FKztvX74sieBHCBFTNwhxSkMln8VX
    RxrdvPsniYkfr4GEr14/Dw845p7zCLllocds4yJado7nr0G/xyc0qQ0PnLY4HIwH
    hdRvx9Aup8u4RYR0+KP4EOOL3HmHwCXgNBJr51Pkxx+tScXmvwC6B4TlKyyVWm4P
    uPSDAr0DQ8ulSPah4Xz5iw==</dsig:SignatureValue>
    <dsig:KeyInfo>
    <dsig:X509Data>
    <dsig:X509IssuerSerial>
    <dsig:X509IssuerName>dnQualifier=vVfvxXz1gOzEDwm2NoiJtcy4REQ=,CN=.192.168.254.3,OU=.cc-ra-1a.s430-2.ca.cinecert.com,O=.ca.cinecert.com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>38981</dsig:X509SerialNumber>
    </dsig:X509IssuerSerial>
    <dsig:X509Certificate>MIIEeDCCA2CgAwIBAgIDAJhFMA0GCSqGSIb3DQEBCwUAMIGGMRkwFwYDVQQKExAu
    Y2EuY2luZWNlcnQuY29tMSkwJwYDVQQLEyAuY2MtcmEtMWEuczQzMC0yLmNhLmNp
    bmVjZXJ0LmNvbTEXMBUGA1UEAxMOLjE5Mi4xNjguMjU0LjMxJTAjBgNVBC4THHZW
    ZnZ4WHoxZ096RUR3bTJOb2lKdGN5NFJFUT0wHhcNMDgwNjE5MjI0NzI2WhcNMjQx
    MjMwMDAwMDAwWjCBgjEZMBcGA1UEChMQLmNhLmNpbmVjZXJ0LmNvbTEpMCcGA1UE
    CxMgLmNjLXJhLTFhLnM0MzAtMi5jYS5jaW5lY2VydC5jb20xEzARBgNVBAMTClNN
    LmRlZmF1bHQxJTAjBgNVBC4THHF0WXI1QzBuMkZBNy9ZSkNXeTBwSno4eEJwTT0w
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkNr9C7ahGRVajMzt0cIp0
    7d6V4h4DkzLTbFTMYPU0xXqmPGLmvpIZ66ooZfm7dJcokEdpOh6VgfNBHnKmsQUx
    cg8F1ofKgR10bzA858wxscaZLiuidlxnvX8ih/0lCYvkyQGqBXm0YboVPQz08uyD
    VzQPLRBfbHwt/ZCXwAMDLRs5Qlm4uZaSP6R296BxJ0vT7jnfGX42OffZaJlm+uoX
    d0vKYLGtywLuR3prGjwtB3iD4NTc3P3W6uKS5AAOAXcefhsYCQNkeYM0iWTFYlo6
    8fZ35Zc4aIsp2MaL0RVquwfN1hRw0+Tuwr0E2c5fB9AkGpFea/VHm85H/JXpWNXv
    AgMBAAGjgfAwge0wCwYDVR0PBAQDAgSwMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYE
    FKrWK+QtJ9hQO/2CQlstKSc/MQaTMIGwBgNVHSMEgagwgaWAFL1X78V89YDsxA8J
    tjaIibXMuEREoYGHpIGEMIGBMRkwFwYDVQQKExAuY2EuY2luZWNlcnQuY29tMSkw
    JwYDVQQLEyAuY2MtcmEtMWEuczQzMC0yLmNhLmNpbmVjZXJ0LmNvbTESMBAGA1UE
    AxMJLmNjLXJhLTJjMSUwIwYDVQQuExxkRmtrUW9oMWNJekJ1TmJDQjlUV3liaG1L
    b0U9ggMAgIIwDQYJKoZIhvcNAQELBQADggEBAGY7W0x3zGauJSGZhjYG8OP3AXN9
    dvRjChn6z1zXRFIlQ9ECmbZBOZTwHYEl1115gJECH6GEHNSPeKUDy9+naeUNdVYm
    NL535xA7lwTyRXp+0D2I8VXf0vE/x7Q8rEkYLlQ+JvPr4YmiFcbit24/U55ehOJ9
    2pVdtpglh0nmtd1mvvPjY3+ZtIkc6It82yV13AV1aj7pXUz4ec6ZnOQ5GI9UFQW/
    b5hObV8X7VOb9jIKL3zzLwKuSgcjpDoIqrynEoC+x2PWLkmS6tYDZxasixwbUBLY
    cAcS6BoN9Qmn188npCiiruBkwPyMs0TUIT3h0pt6+tjp3c9dDCGv2tjgpD8=
    </dsig:X509Certificate>
    </dsig:X509Data>
    <dsig:X509Data>
    <dsig:X509IssuerSerial>
    <dsig:X509IssuerName>dnQualifier=dFkkQoh1cIzBuNbCB9TWybhmKoE=,CN=.cc-ra-2c,OU=.cc-ra-1a.s430-2.ca.cinecert.com,O=.ca.cinecert.com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>32898</dsig:X509SerialNumber>
    </dsig:X509IssuerSerial>
    <dsig:X509Certificate>MIIEcTCCA1mgAwIBAgIDAICCMA0GCSqGSIb3DQEBCwUAMIGBMRkwFwYDVQQKExAu
    Y2EuY2luZWNlcnQuY29tMSkwJwYDVQQLEyAuY2MtcmEtMWEuczQzMC0yLmNhLmNp
    bmVjZXJ0LmNvbTESMBAGA1UEAxMJLmNjLXJhLTJjMSUwIwYDVQQuExxkRmtrUW9o
    MWNJekJ1TmJDQjlUV3liaG1Lb0U9MB4XDTA4MDYxOTIyNDY1MVoXDTI0MTIzMTAw
    MDAwMFowgYYxGTAXBgNVBAoTEC5jYS5jaW5lY2VydC5jb20xKTAnBgNVBAsTIC5j
    Yy1yYS0xYS5zNDMwLTIuY2EuY2luZWNlcnQuY29tMRcwFQYDVQQDEw4uMTkyLjE2
    OC4yNTQuMzElMCMGA1UELhMcdlZmdnhYejFnT3pFRHdtMk5vaUp0Y3k0UkVRPTCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMPBTSPhpKBPe9U81+hAgaV1
    yo05zLbqrpfyXuM53NVUZ8EE1uFaK3zqolABYtWM8LAUXzv2LD+/og0DRPfPAj66
    pT4DA34Xf5mNjYzHt60Mfm6clUxSQ42vdqto8fb9XnGcwgKuSyzGpYrJ5tTD/aiP
    pD6FA/0IQ3ecAXWXKDXOIP/tEzQxcPwo9AkvSXp/Ne0MBovia3EoDx75DFs5BJ16
    UTFOkATpDxw8e7rLeNkXrwGIpNw9vWYn3NiZwFRTN2w3Ck6APeJNmns2dRciy44m
    Glw5GV4DJh5d8ZXiCnRk2nhY3V/UxY4FXhoHxWE+wKwEPzHKfcnxaHO1zPCoAM8C
    AwEAAaOB6jCB5zALBgNVHQ8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
    HQ4EFgQUvVfvxXz1gOzEDwm2NoiJtcy4REQwgaQGA1UdIwSBnDCBmYAUdFkkQoh1
    cIzBuNbCB9TWybhmKoGhfKR6MHgxGTAXBgNVBAoTEC5jYS5jaW5lY2VydC5jb20x
    IDAeBgNVBAsTFy5zNDMwLTIuY2EuY2luZWNlcnQuY29tMRIwEAYDVQQDEwkuY2Mt
    cmEtMWExJTAjBgNVBC4THEsrRERkcDF5R1dsbmVXYVgzVUlvSVh0QVFUMD2CAwCP
    xzANBgkqhkiG9w0BAQsFAAOCAQEAGL/6PXYURL2DOJmhCQ65Sv8CJTBaNWJagVdM
    AYOWAJHENot0nPd60CEuM7Ct0cdyEPpeGgBRFRqdNie2JshCeF+AJo04suBmrv1w
    9Kd9CyAHsRSuMX3GcNq8r5MekxuzX9DOmke4xZIn29XgqM0iq3JcfKvPeAFrPPPg
    o7chlGljzgIV8KyeA3bIDxunP5akKE84wYD0DUDhsp5+BxTazMT6vTq9ekHVvjxP
    p9dR1EPV96PJ3zno7Y47wYy2x6P7z/EhEmA0MHLV7F6Xgdh/6JXWRMpxoqaGis+F
    XXihVTpytQYDjkszHzu+HTFKHmIUKzePAdT9qZr/dwFZ5Gdivg==
    </dsig:X509Certificate>
    </dsig:X509Data>
    <dsig:X509Data>
    <dsig:X509IssuerSerial>
    <dsig:X509IssuerName>dnQualifier=K\+DDdp1yGWlneWaX3UIoIXtAQT0=,CN=.cc-ra-1a,OU=.s430-2.ca.cinecert.com,O=.ca.cinecert.com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>36807</dsig:X509SerialNumber>
    </dsig:X509IssuerSerial>
    <dsig:X509Certificate>MIIEWTCCA0GgAwIBAgIDAI/HMA0GCSqGSIb3DQEBCwUAMHgxGTAXBgNVBAoTEC5j
    YS5jaW5lY2VydC5jb20xIDAeBgNVBAsTFy5zNDMwLTIuY2EuY2luZWNlcnQuY29t
    MRIwEAYDVQQDEwkuY2MtcmEtMWExJTAjBgNVBC4THEsrRERkcDF5R1dsbmVXYVgz
    VUlvSVh0QVFUMD0wHhcNMDcwMzI3MDcxMzU2WhcNMjUwMTAxMDAwMDAwWjCBgTEZ
    MBcGA1UEChMQLmNhLmNpbmVjZXJ0LmNvbTEpMCcGA1UECxMgLmNjLXJhLTFhLnM0
    MzAtMi5jYS5jaW5lY2VydC5jb20xEjAQBgNVBAMTCS5jYy1yYS0yYzElMCMGA1UE
    LhMcZEZra1FvaDFjSXpCdU5iQ0I5VFd5YmhtS29FPTCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAOxGeJOQ2NzJ6mEAu4Ni+YGrI0fqwhZvKylDgbafJtFB
    3/2GTEyYZgCETXyX2YugAh3iie34SUikY3YeF61cSNMGUvKMYxogoo98eK4KjA5l
    T6xPZcRvBL7ln7GgKd4IdwdG/3EzUjIqR78tNcnl/cgJ10bGWGgcNzAzW1Wh+lfG
    b+R34liZxaQ8snb1rSJ/VVkf39ueq2V0EhYs2qzFEcHU9Kha5VTtdP44xDvOF5Sy
    22ig75CdKcJHdgDs/8PJsbrFkvVzb7sEdS4lQ+STJdEwMTrDRk0i+iG5hxCpZJAc
    NFr4bXLu5W8MFCQMDfIHpjaEy84xaGtlLhzvHK6mUAECAwEAAaOB4TCB3jALBgNV
    HQ8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBAzAdBgNVHQ4EFgQUdFkkQoh1cIzB
    uNbCB9TWybhmKoEwgZsGA1UdIwSBkzCBkIAUK+DDdp1yGWlneWaX3UIoIXtAQT2h
    c6RxMG8xGTAXBgNVBAoTEC5jYS5jaW5lY2VydC5jb20xGTAXBgNVBAsTEC5jYS5j
    aW5lY2VydC5jb20xEDAOBgNVBAMTBy5zNDMwLTIxJTAjBgNVBC4THDhPOFc4b1lI
    bGY5N1k4bjBrZEFnTVU3L2pVVT2CAwDHFjANBgkqhkiG9w0BAQsFAAOCAQEA3Qqg
    ixs7PWXx0lT+b7KUAtQ6yIwqJWJ6ZP6AiVi+uo/yiKMgziKw4D+/x5Uq2qOgorlc
    +jTPVr+Gln7IV/HwSvc3HdduGeNy5dg2LomkP8gqIXRkd8UcePji3KUtnuax0jpy
    LXymO+mQzZiFPJY99xthgOTI0ksjZK1ryxbC9S3JqmRDtj0kvZyT/lvDHS3xwitO
    vm3Y7nYOIXLDdC6NZdsi/GaSSOOO0KQJzgJ6afFOlzYMbz1/sSiOd60tmIuztSbf
    exEP1qeNXRCHIRntXOfBlXJvGLu9vwVOeOMK43MZjsQLxgfv8MxLYYwx6crkhWRm
    Nk28wnTwGFz93rhRSg==
    </dsig:X509Certificate>
    </dsig:X509Data>
    <dsig:X509Data>
    <dsig:X509IssuerSerial>
    <dsig:X509IssuerName>dnQualifier=8O8W8oYHlf97Y8n0kdAgMU7/jUU=,CN=.s430-2,OU=.ca.cinecert.com,O=.ca.cinecert.com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>50966</dsig:X509SerialNumber>
    </dsig:X509IssuerSerial>
    <dsig:X509Certificate>MIIETDCCAzSgAwIBAgIDAMcWMA0GCSqGSIb3DQEBCwUAMG8xGTAXBgNVBAoTEC5j
    YS5jaW5lY2VydC5jb20xGTAXBgNVBAsTEC5jYS5jaW5lY2VydC5jb20xEDAOBgNV
    BAMTBy5zNDMwLTIxJTAjBgNVBC4THDhPOFc4b1lIbGY5N1k4bjBrZEFnTVU3L2pV
    VT0wHhcNMDcwMzI3MDcxMzA4WhcNMjYwMTAxMDAwMDAwWjB4MRkwFwYDVQQKExAu
    Y2EuY2luZWNlcnQuY29tMSAwHgYDVQQLExcuczQzMC0yLmNhLmNpbmVjZXJ0LmNv
    bTESMBAGA1UEAxMJLmNjLXJhLTFhMSUwIwYDVQQuExxLK0REZHAxeUdXbG5lV2FY
    M1VJb0lYdEFRVDA9MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8ztG
    Pz71+8WrCu6NwAbIUetNjBORWcqXt7a62UCEHu5mbb/ca+OAV90gRPLL1LqbzsJU
    u8DoptMYhsQ/+d+Ln1fIUjsJhQIJKn5lQxIhiIPJ6iGeKo0+srN/ugAOKru9h/9e
    I9upHpCOo4lfyIKHhkHZAWkkIeSzyM8/VqYF66TGsndjofiwHW8LG964EFpRWouO
    j1reAP5CUc9Ftj8IVdEUcIcexClzwcJqwePWQpjXne5e3w4lRI8TgBiCz0VSgXk1
    9oSEud3n4Pdo+FjvDCOCIWYHMYyjLB+/atnpShCbsstYJ/cc68ad+W27y88HOYSM
    9PGYuamQbUtid9zsIQIDAQABo4HnMIHkMAsGA1UdDwQEAwIBBjASBgNVHRMBAf8E
    CDAGAQH/AgEEMB0GA1UdDgQWBBQr4MN2nXIZaWd5ZpfdQighe0BBPTCBoQYDVR0j
    BIGZMIGWgBTw7xbyhgeV/3tjyfSR0CAxTv+NRaFzpHEwbzEZMBcGA1UEChMQLmNh
    LmNpbmVjZXJ0LmNvbTEZMBcGA1UECxMQLmNhLmNpbmVjZXJ0LmNvbTEQMA4GA1UE
    AxMHLnM0MzAtMjElMCMGA1UELhMcOE84VzhvWUhsZjk3WThuMGtkQWdNVTcvalVV
    PYIJALhGwbfi5fVsMA0GCSqGSIb3DQEBCwUAA4IBAQAPYRpoaH9vKLut/HngT3q7
    x2GWz+QKMxbDKNY21VTEleADF3jdWWz+pUf8adnBS3TScMQtmWWUDIXSpXeUQI07
    4ptSOze0pk13hP2VqZWu5DYosL2Y9mDhW+fxN/15EjbzwpM7/KUPGPOdL4ytSqqT
    wKSApLAK/9yWrchF5OJup1/zcIBuzNP0v5wi63XPByVU1RhcWseyYbwxo452mPB2
    3JOUq6tr3vvFfXagVf8/0wFTV3wtAXpNPQKjhMvz5n4/N/EFqXrknnlcY9dWopFI
    uLIrGE9FVxvsNJ1YzANC9Y6/vCKaRalwQ62W1nClQ/WzQn0C46hkuNxTI4diIm3+
    </dsig:X509Certificate>
    </dsig:X509Data>
    <dsig:X509Data>
    <dsig:X509IssuerSerial>
    <dsig:X509IssuerName>dnQualifier=8O8W8oYHlf97Y8n0kdAgMU7/jUU=,CN=.s430-2,OU=.ca.cinecert.com,O=.ca.cinecert.com</dsig:X509IssuerName>
    <dsig:X509SerialNumber>13278513546878383468</dsig:X509SerialNumber>
    </dsig:X509IssuerSerial>
    <dsig:X509Certificate>MIIESTCCAzGgAwIBAgIJALhGwbfi5fVsMA0GCSqGSIb3DQEBCwUAMG8xGTAXBgNV
    BAoTEC5jYS5jaW5lY2VydC5jb20xGTAXBgNVBAsTEC5jYS5jaW5lY2VydC5jb20x
    EDAOBgNVBAMTBy5zNDMwLTIxJTAjBgNVBC4THDhPOFc4b1lIbGY5N1k4bjBrZEFn
    TVU3L2pVVT0wHhcNMDcwMzEyMTQ1MjEyWhcNMjcwMzA3MTQ1MjEyWjBvMRkwFwYD
    VQQKExAuY2EuY2luZWNlcnQuY29tMRkwFwYDVQQLExAuY2EuY2luZWNlcnQuY29t
    MRAwDgYDVQQDEwcuczQzMC0yMSUwIwYDVQQuExw4TzhXOG9ZSGxmOTdZOG4wa2RB
    Z01VNy9qVVU9MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAph/idpSe
    h3CuscvGWmU+i2nZcyQAWJkztubSvukI9OMyLdLcXA4b1sRpxzkzFJ4NGyloHoVG
    OW3dhm/HrUdbiICHgEzMOJq33bBvZvf8OIw6zbSkTJCu2NbX8rBkjxs72i2ANjXJ
    LBJz4hHi3KQ0027fZRQ80uksUA96pN4xSkUEdz9cm2IrjmIRTXBKxxL7VvG2sK4j
    DodedAOQPMczKYeA4CC64cFpPyl9s4mbZJ6roNahBX3p5zmxk9C/qWDEZeiJoPQS
    +gDEfRJFTLOkH2/onrE1Gw5/ErBzhZcfh6uOYUt3YlEYZDN6cJuUyPr3BaSI2rC2
    vB/Ex8HioTm4rwIDAQABo4HnMIHkMB0GA1UdDgQWBBTw7xbyhgeV/3tjyfSR0CAx
    Tv+NRTCBoQYDVR0jBIGZMIGWgBTw7xbyhgeV/3tjyfSR0CAxTv+NRaFzpHEwbzEZ
    MBcGA1UEChMQLmNhLmNpbmVjZXJ0LmNvbTEZMBcGA1UECxMQLmNhLmNpbmVjZXJ0
    LmNvbTEQMA4GA1UEAxMHLnM0MzAtMjElMCMGA1UELhMcOE84VzhvWUhsZjk3WThu
    MGtkQWdNVTcvalVVPYIJALhGwbfi5fVsMBIGA1UdEwEB/wQIMAYBAf8CAQUwCwYD
    VR0PBAQDAgIEMA0GCSqGSIb3DQEBCwUAA4IBAQBXNS39cY/a0bIUJRqL+LfI7lIw
    EY6sXABbwmUUO42Y/eS7gbpacJnSKrGtdRFWhoC0cCNR1QWrn4IOsKNRi3ed0kCo
    ccMjlaUFnUhjLUW5xQSx2w09v+bUkPlUm2hjFxOneFPbSCiWTrlmDFRqPz8+rvpT
    Q7tMBqEDNFtjrB/8KJmJwajf5CaamyFPqc2aMYj9B7GPtzcKPQlbQeAGf+x4l7Iz
    Y5iOkXqv8VqwxV3ngjV9RlLfPN3OhoBH9jTXV8kNe+mkzqQhhf6HYI50FDOVR6yC
    C7Fa0KtH0mnRwmZZKW/8vPOIeffauUs2BVVGz/K6Xvk1XWPz2O34IfGIC8r9
    </dsig:X509Certificate>
    </dsig:X509Data>
    </dsig:KeyInfo>
    </dsig:Signature>
    </DCinemaSecurityMessage>
"""

class TestLockpick(unittest.TestCase):
    """
        Units tests for the Lockpick Python client
        """
    
    def setUp(self):
        self.lockpick = Lockpick(_TESTUSER, _TESTPASS, _TESTHOST)
    
    def test_version(self):
        self.assertTrue(self.lockpick.version == 0.01)
    
    def test_get_kdm(self):
        kdm = self.lockpick.get_kdm('daf5f223-5924-4a43-8f3b-e34a0b13f4b4')
        for k in kdm.keys():
            self.assertTrue(k in ('id', 'text', 'subject', 'valid_from', 'valid_to', 'cpl_id', 'cpl_text', 'xml', 'status', 'user', 'signer',))
        for k in kdm['subject'].keys():
            self.assertTrue(k in ('thumbprint', 'name', 'org', 'unit',))
        self.assertEqual(kdm['subject']['thumbprint'], 'dCxHtnikb+RSfBAuRkIVqPxaY4I=')
    
    def test_save_kdm(self):
        result = self.lockpick.save_kdm(_TESTKDM)
        self.assertTrue(not 'errors' in result.keys())
        self.assertEqual(result['message'], 'Saved KDM')

    def test_get_kdms_from_thumbprint(self):
        kdms = self.lockpick.get_kdms_from_thumbprint('dCxHtnikb\\+RSfBAuRkIVqPxaY4I=')
        self.assertTrue(len(kdms))

if __name__ == '__main__':
    unittest.main()
